unix_like_task:
  matrix:
    # Debian ####################################
    - name: "Debian Bookworm"
      container:
        image: debian:bookworm-slim
        cpu: 1
        memory: 1G
      install_packages_script:
        - apt update
        - apt install -y git cmake g++
    - name: "Debian Bullseye"
      container: 
        image: debian:bullseye-slim
        cpu: 1
        memory: 1G
      install_packages_script:
        - apt update
        - apt install -y git cmake g++
    - name: "Debian testing"
      container: 
        image: debian:testing-slim
        cpu: 1
        memory: 1G
      env:
        DEPLOY: "yes"
      install_packages_script:
        - apt update
        - apt install -y git cmake g++
    # Fedora ####################################
    - name: "Fedora latest"
      container:
        image: fedora:latest
        cpu: 1
        memory: 1G
      install_packages_script:
        - dnf install -y git cmake g++
    # Alpine ####################################
    - name: "Alpine latest"
      container:
        image: alpine:latest
        cpu: 1
        memory: 1G
      install_packages_script:
        - apk add git cmake g++ make
    - name: "Alpine edge"
      container:
        image: alpine:edge
        cpu: 1
        memory: 1G
      install_packages_script:
        - apk add git cmake g++ make
    # FreeBSD ###################################
    - name: "FreeBSD 13.1"
      freebsd_instance:
        image_family: freebsd-13-1
        cpu: 1
        memory: 1G
      install_packages_script:
        - pkg install -y git cmake
    - name: "FreeBSD 14.0"
      freebsd_instance:
        image_family: freebsd-14-0-snap
        cpu: 1
        memory: 1G
      install_packages_script:
        - pkg install -y git cmake
    # Mac OSX ###################################
    - name: "Mac OSX Ventura"
      macos_instance:
        image: ghcr.io/cirruslabs/macos-ventura-base:latest

  lab_01_script:
    - sh ci/test-patch.sh https://git.ik.bme.hu/Prog2/labor_peldak/lab_01.git lab_01

  lab_02_script:
    - sh ci/test-patch.sh https://git.ik.bme.hu/Prog2/labor_peldak/lab_02.git lab_02

  lab_03_script:
    - sh ci/test-patch.sh https://git.ik.bme.hu/Prog2/labor_peldak/lab_03.git lab_03

  lab_04_script:
    - sh ci/test-patch.sh https://git.ik.bme.hu/Prog2/labor_peldak/lab_04.git lab_04

  lab_05_script:
    - sh ci/test-patch.sh https://git.ik.bme.hu/Prog2/labor_peldak/lab_05.git lab_05

  lab_06_script:
    - sh ci/test-patch.sh https://git.ik.bme.hu/Prog2/labor_peldak/lab_06.git lab_06
  
  lab_07_script:
    - sh ci/test-patch.sh https://git.ik.bme.hu/Prog2/labor_peldak/lab_07.git lab_07

  lab_08_script:
    - sh ci/test-patch.sh https://git.ik.bme.hu/Prog2/labor_peldak/lab_08.git lab_08

  lab_09_script:
    - sh ci/test-patch.sh https://git.ik.bme.hu/Prog2/labor_peldak/lab_09.git lab_09

  lab_10_script:
    - sh ci/test-patch.sh https://git.ik.bme.hu/Prog2/labor_peldak/lab_10.git lab_10

  lab_11_script:
    - sh ci/test-patch.sh https://git.ik.bme.hu/Prog2/labor_peldak/lab_11.git lab_11

  cppswap_script:
    - sh ci/test-patch.sh https://git.ik.bme.hu/Prog2/ell_feladat/CPPswap.git cppswap

  nem_oo_script:
    - sh ci/test-patch.sh https://git.ik.bme.hu/Prog2/ell_feladat/Nem_OO.git nem_oo

  cppellenallas_script:
    - sh ci/test-patch.sh https://git.ik.bme.hu/Prog2/ell_feladat/CppEllenallas.git cppellenallas

  clonable_hetero_script:
    - sh ci/test-patch.sh https://git.ik.bme.hu/Prog2/ell_feladat/ClonableHetero.git clonable_hetero

  cpp_ember_script:
    - sh ci/test-patch.sh https://git.ik.bme.hu/Prog2/ell_feladat/CppEmber.git cpp_ember 

  cpp_hetero_script:
    - sh ci/test-patch.sh https://git.ik.bme.hu/Prog2/ell_feladat/CppHetero.git cpp_hetero

  cpp_monoton_script:
    - sh ci/test-patch.sh https://git.ik.bme.hu/Prog2/ell_feladat/CppMonoton.git cpp_monoton

  cpp_vektor_script:
    - sh ci/test-patch.sh https://git.ik.bme.hu/Prog2/ell_feladat/CppVektor.git cpp_vektor

  genetika_script:
    - sh ci/test-patch.sh https://git.ik.bme.hu/Prog2/szorgalmi_feladatok/genetika.git genetika

  pstring_script:
    - sh ci/test-patch.sh https://git.ik.bme.hu/Prog2/ell_feladat/PString.git pstring

  ustring_script:
    - sh ci/test-patch.sh https://git.ik.bme.hu/Prog2/ell_feladat/UString.git ustring
  
  cpp_tar_script:
    - sh ci/test-patch.sh https://git.ik.bme.hu/Prog2/ell_feladat/CppTar.git cpp_tar 

  deploy_script:
    - sh ci/deploy.sh


windows_task:
  env:
    PATH: C:\ProgramData\chocolatey\bin;C:\Program Files\CMake\bin;C:\tools\msys64\ucrt64\bin;C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin;%PATH%

  matrix:
    # Windows ###################################
    - name: "Windows Server Core 2019 -- MSYS2"
      windows_container:
        image: cirrusci/windowsservercore:2019
      install_packages_script:
        - choco install -y cmake
        - choco install -y ninja
        - choco install -y msys2
        - C:\tools\msys64\msys2_shell.cmd -defterm -no-start -c "pacman --noconfirm -S mingw-w64-ucrt-x86_64-gcc"
      env:
        DO_MSYS2: yes
    - name: "Windows Server Core 2019 -- MinGW"
      windows_container:
        image: cirrusci/windowsservercore:2019
      install_packages_script:
        - choco install -y cmake
        - choco install -y mingw
      env:
        DO_MINGW: yes
    - name: "Windows Server Core 2019 -- Visual Studio 17 2022"
      windows_container:
        image: cirrusci/windowsservercore:2019
      install_packages_script:
        - choco install -y cmake
        - choco install visualstudio2022buildtools -y --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.VC.Redist.14.Latest --add Microsoft.Component.VC.Runtime.UCRTSDK --add Microsoft.VisualStudio.Component.Windows11SDK.22621 --add Microsoft.VisualStudio.Component.VC.ATL"
      env:
        DO_MSVC: yes

  cppswap_script:
    - ci\test-patch.bat https://git.ik.bme.hu/Prog2/ell_feladat/CPPswap.git cppswap

  lab_01_script:
    - ci\test-patch.bat https://git.ik.bme.hu/Prog2/labor_peldak/lab_01.git lab_01

  nem_oo_script:
    - ci\test-patch.bat https://git.ik.bme.hu/Prog2/ell_feladat/Nem_OO.git nem_oo

  lab_02_script:
    - ci\test-patch.bat https://git.ik.bme.hu/Prog2/labor_peldak/lab_02.git lab_02

  lab_03_script:
    - ci\test-patch.bat https://git.ik.bme.hu/Prog2/labor_peldak/lab_03.git lab_03

  cppellenallas_script:
    - ci\test-patch.bat https://git.ik.bme.hu/Prog2/ell_feladat/CppEllenallas.git cppellenallas

  lab_04_script:
    - ci\test-patch.bat https://git.ik.bme.hu/Prog2/labor_peldak/lab_04.git lab_04

  lab_05_script:
    - ci\test-patch.bat https://git.ik.bme.hu/Prog2/labor_peldak/lab_05.git lab_05

  lab_06_script:
    - ci\test-patch.bat https://git.ik.bme.hu/Prog2/labor_peldak/lab_06.git lab_06

  lab_07_script:
    - ci\test-patch.bat https://git.ik.bme.hu/Prog2/labor_peldak/lab_07.git lab_07

  lab_08_script:
    - ci\test-patch.bat https://git.ik.bme.hu/Prog2/labor_peldak/lab_08.git lab_08

  clonable_hetero_script:
    - ci\test-patch.bat https://git.ik.bme.hu/Prog2/ell_feladat/ClonableHetero.git clonable_hetero

  cpp_ember_script:
    - ci\test-patch.bat https://git.ik.bme.hu/Prog2/ell_feladat/CppEmber.git cpp_ember 
  
  cpp_tar_script:
    - ci\test-patch.bat https://git.ik.bme.hu/Prog2/ell_feladat/CppTar.git cpp_tar 

  cpp_hetero_script:
    - ci\test-patch.bat https://git.ik.bme.hu/Prog2/ell_feladat/CppHetero.git cpp_hetero

  cpp_monoton_script:
    - ci\test-patch.bat https://git.ik.bme.hu/Prog2/ell_feladat/CppMonoton.git cpp_monoton

  cpp_vektor_script:
    - ci\test-patch.bat https://git.ik.bme.hu/Prog2/ell_feladat/CppVektor.git cpp_vektor

  genetika_script:
    - ci\test-patch.bat https://git.ik.bme.hu/Prog2/szorgalmi_feladatok/genetika.git genetika

  pstring_script:
    - ci\test-patch.bat https://git.ik.bme.hu/Prog2/ell_feladat/PString.git pstring

  ustring_script:
    - ci\test-patch.bat https://git.ik.bme.hu/Prog2/ell_feladat/UString.git ustring

