unix_like_task:
  matrix:
    # Debian ####################################
    - name: "Debian Bookworm"
      container:
        image: debian:bookworm-slim
      env:
        TEST_FILE: sh ci/test-patch.sh
      get_git_script:
        - apt install -y git
    - name: "Debian Bullseye"
      container: 
        image: debian:bullseye-slim
      env:
        TEST_FILE: sh ci/test-patch.sh
      get_git_script:
        - apt install -y git
    - name: "Debian testing"
      container: 
        image: debian:testing-slim
      env:
        TEST_FILE: sh ci/test-patch.sh
      get_git_script:
        - apt install -y git
    # Fedora ####################################
    - name: "Fedora latest"
      container:
        image: fedora:latest
      env:
        TEST_FILE: sh ci/test-patch.sh
      get_git_script:
        - dnf install -y git
    # Alpine ####################################
    - name: "Alpine latest"
      container:
        image: alpine:latest
      env:
        TEST_FILE: sh ci/test-patch.sh
      get_git_script:
        - apk add git
    - name: "Alpine edge"
      container:
        image: alpine:edge
      env:
        TEST_FILE: sh ci/test-patch.sh
      get_git_script:
        - apk add git
    # FreeBSD ###################################
    - name: "FreeBSD 13.1"
      freebsd_instance:
        image_family: freebsd-13-1
      env:
        TEST_FILE: sh ci/test-patch.sh
      get_git_script:
        - pkg install -y git
    - name: "FreeBSD 14.0"
      freebsd_instance:
        image_family: freebsd-14-0-snap
      env:
        TEST_FILE: sh ci/test-patch.sh
      get_git_script:
        - pkg install -y git
    # Mac OSX ###################################
    - name: "Mac OSX "
      macos_instance:
        image: ghcr.io/cirruslabs/macos-ventura-base:latest
      env:
        TEST_FILE: sh ci/test-patch.sh
  
  cppswap_script:
    - ${TEST_FILE} https://git.ik.bme.hu/Prog2/ell_feladat/CPPswap.git cppswap
  
  lab_01_script:
    - ${TEST_FILE} https://git.ik.bme.hu/Prog2/labor_peldak/lab_01.git lab_01
  
  nem_oo_script:
    - ${TEST_FILE} https://git.ik.bme.hu/Prog2/ell_feladat/Nem_OO.git nem_oo

windows_task:
  matrix:
    # Windows ###################################
    - name: "Windows Server Core 2019"
      windows_container:
        image: cirrusci/windowsservercore:2019

  cppswap_script:
    - ci\test-patch.bat https://git.ik.bme.hu/Prog2/ell_feladat/CPPswap.git cppswap
  
  lab_01_script:
    - ci\test-patch.bat https://git.ik.bme.hu/Prog2/labor_peldak/lab_01.git lab_01
  
  nem_oo_script:
    - ci\test-patch.bat https://git.ik.bme.hu/Prog2/ell_feladat/Nem_OO.git nem_oo