= A programozás alapjai 2 labor beta

image:https://badgen.net/github/checks/bodand/prog2-lab-beta/trunk[]

A programozás alapjai 2 tárgy laborjainak új CMake alapú szervezésének béta verziója.

Ez a raktár tartalmazza azokat a .patch fájlokat, amelyek egy új, modern CMake
alapú fordítási rendszert vezetnek be a laborokra.

Ez azt takarja, hogy az eddig használt Makefile, Code::Blocks projekt fájl, és
Visual Studio solutionök helyett most egy centralizált CMake script kezeli a 
projekt konfigurálását és fordítását.

Ez azért előnyös, mert így most mindenki közel tetszőleges platformon közel 
tetszőleges fejlesztő környezettel tudja megoldani a feladatokat, mert csak 
CMake-kel le kell generáltatni a neki szükséges projekt fájlt.
Legyen ez Windows/Visual Studio, Linux/vim, vagy OSX/VS Code.

Emellett, sok fejlesztőkörnyezet natívan (vagy pluginnal) támogatja a CMake 
projekteket. Így szimplán csak meg kell nyitni a mappát, amelyikben a projekt 
van, és rögtön fel ismeri a környezet.

.HSZK 
A HSZK felkészültsége kicsit nehezíti ezt a folyamatot, mert explicité szükség 
van VS solution fájlok generálására, ahelyett, hogy csak meg lehessen nyitni 
a CMake projekteket.
Ennek orvoslására ebben a félévben még sajnos nem került sor, úgyhogy még 
az ideiglenes megoldást kell alkalmazni.

== Használat

Minden laborhoz tartozik egy saját .patch fájl, amit git-tel vagy patch(1)-el 
lehet alkalmazni.

Ehhez le kell tölteni a hivatalos labor feladat raktár, és bemásolni a megfelelő
\.patch fájlt ebből a mappából.
Például a CPPswap feladat leklónozása után a cppswap.patch fájlt kell bemásolni a
mappába.

Ez után, alkalmazni kell a patch fájlt, amit vagy a git-apply(1) vagy patch(1)
programokkal lehetséges. Utóbbi platformfüggő, úgyhogy a git-apply alapú megoldást
mutatjuk be, ami működik Windowson is.

[source,bash]
----
git apply --reject --ignore-space-change --ignore-whitespace --whitespace=fix <patch-file>
----

Ez a folyamat generál egy új CMakeLists.txt fájlt a mappában, amelyet lehet használni
a projekt konfigurálására.
Emellett feltakarítja az így fölöslegessé vált régi rendszer fájljait.

Minden mappában generálódik egy BUILD.txt fájl, amely a rendszer használatának folyamatát 
írja le a legtöbb (általam) ismert fejlesztő környezet esetére.

== Feedback 

Ha akármilyen probléma merül fel, akkor a bodand@proton.me címen próbálok mihamarabb 
segítséget nyújtani, illetve a JPorta email rendszerében, bár előbbi preferált.

